# Generated by Django 2.0.6 on 2018-06-18 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alturaPlanta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grosorTallo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numeroHojas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pesoRacimo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costoHectarea', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('kgCosechados', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('precioKg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('utilidadEsperada', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoHectarea', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kgCosechados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioKg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('utilidadEsperada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cosecha', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.Cosecha')),
            ],
        ),
    ]
