# Generated by Django 2.0.6 on 2018-06-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_auto_20180618_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosecha',
            name='alturaPlanta',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='costoHectarea',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='grosorTallo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='numeroHojas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='pesoRacimo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='precioKg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
