# Generated by Django 2.0.6 on 2018-06-18 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='usuarioSim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
