# Generated by Django 2.0.6 on 2018-06-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacion', '0002_auto_20180617_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='boro',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='calcio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='fosforo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='luminosidad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='lvlMar',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='magnesio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='pluviosidad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='potasio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='profundidad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='simulacioncostoproduccion',
            name='zinc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
